import { Resend } from 'resend';

/**
 * Resend client — server-only.
 *
 * Delivers all APEXSTORAGE-branded authentication emails.
 * Authentication links themselves are always generated by the
 * Firebase Admin SDK; Resend is only the delivery channel.
 *
 * Required env vars:
 *   RESEND_API_KEY   — Resend API key
 *   EMAIL_FROM       — Sender identity, e.g. "APEXSTORAGE <security@apexstorage.site>"
 *   SUPPORT_EMAIL    — Support inbox shown in email footers
 *   APP_URL          — Public application URL used as the Firebase action continue URL
 *   REPLY_TO         — (optional) Reply-To address; defaults to SUPPORT_EMAIL
 */

let cachedClient: Resend | null = null;

export function getResend(): Resend {
  if (cachedClient) return cachedClient;
  if (!process.env.RESEND_API_KEY) {
    throw new Error('Resend is not configured. Set RESEND_API_KEY.');
  }
  cachedClient = new Resend(process.env.RESEND_API_KEY);
  return cachedClient;
}

/** Sender identity for every outgoing APEXSTORAGE email. */
export const EMAIL_FROM =
  process.env.EMAIL_FROM || 'APEXSTORAGE <security@apexstorage.site>';

/** Reply-To address for every outgoing APEXSTORAGE email. */
export const REPLY_TO =
  process.env.REPLY_TO || process.env.SUPPORT_EMAIL || 'support@apexstorage.site';

/** Support inbox shown in email footers. */
export const SUPPORT_EMAIL =
  process.env.SUPPORT_EMAIL || 'support@apexstorage.site';

/** Public application URL used as the Firebase action continue URL. */
export const APP_URL = (process.env.APP_URL || 'http://localhost:3000').replace(/\/$/, '');
