import { Resend } from 'resend';

/**
 * Resend client — server-only.
 *
 * Delivers all APEXSTORAGE-branded authentication emails.
 * Authentication links themselves are always generated by the
 * Firebase Admin SDK; Resend is only the delivery channel.
 *
 * Required env vars:
 *   RESEND_API_KEY   — Resend API key
 *   EMAIL_FROM       — Sender identity, e.g. "APEXSTORAGE <security@apexstorage.site>"
 *   SUPPORT_EMAIL    — Support inbox shown in email footers
 *   APP_URL          — Public application URL used as the Firebase action continue URL
 *   REPLY_TO         — (optional) Reply-To address; defaults to SUPPORT_EMAIL
 */

let cachedClient: Resend | null = null;

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i;
const DEFAULT_APP_URL = 'http://localhost:3000';

function normalizeAppUrl(rawUrl?: string): string {
  const value = (rawUrl || DEFAULT_APP_URL).trim().replace(/\/+$/, '');

  try {
    const url = new URL(value);
    if (url.protocol !== 'http:' && url.protocol !== 'https:') {
      throw new Error('Unsupported protocol');
    }
    return url.origin;
  } catch {
    throw new Error(`APP_URL is invalid. Set APP_URL to a full http(s) URL, for example ${DEFAULT_APP_URL}.`);
  }
}

function validateSenderIdentity(from: string): void {
  const trimmed = from.trim();
  const emailMatch = trimmed.match(/<([^>]+)>$/);
  const email = emailMatch ? emailMatch[1] : trimmed;

  if (!EMAIL_RE.test(email)) {
    throw new Error('EMAIL_FROM is invalid. Use a valid sender address, for example "APEXSTORAGE <security@apexstorage.site>".');
  }
  if (/yourdomain\.com/i.test(email)) {
    throw new Error('EMAIL_FROM still uses the placeholder yourdomain.com. Configure a sender from a verified Resend domain.');
  }
}

export function getResend(): Resend {
  if (cachedClient) return cachedClient;
  if (!process.env.RESEND_API_KEY?.trim()) {
    throw new Error('Resend is not configured. Set RESEND_API_KEY.');
  }
  cachedClient = new Resend(process.env.RESEND_API_KEY.trim());
  return cachedClient;
}

/** Sender identity for every outgoing APEXSTORAGE email. */
export const EMAIL_FROM =
  process.env.EMAIL_FROM || 'APEXSTORAGE <security@apexstorage.site>';

/** Reply-To address for every outgoing APEXSTORAGE email. */
export const REPLY_TO =
  process.env.REPLY_TO || process.env.SUPPORT_EMAIL || 'support@apexstorage.site';

/** Support inbox shown in email footers. */
export const SUPPORT_EMAIL =
  process.env.SUPPORT_EMAIL || 'support@apexstorage.site';

/** Public application URL used as the Firebase action continue URL. */
export function getAppUrl(): string {
  return normalizeAppUrl(process.env.APP_URL);
}

/**
 * True when a URL is a real public https URL that is safe to embed in
 * outbound email. Emails must never contain loopback/private/development
 * URLs — mailbox providers classify messages linking to them as spam or
 * phishing (this is what kept the welcome email out of the inbox).
 */
export function isPublicWebUrl(raw: string): boolean {
  try {
    const url = new URL(raw);
    if (url.protocol !== 'https:') return false;
    const host = url.hostname.toLowerCase();
    if (host === 'localhost' || host.endsWith('.local') || host.endsWith('.localhost')) return false;
    if (host === '127.0.0.1' || host.startsWith('127.')) return false;
    if (/^(10\.|192\.168\.)/.test(host)) return false;
    if (/^172\.(1[6-9]|2\d|3[01])\./.test(host)) return false;
    return true;
  } catch {
    return false;
  }
}

export function assertEmailConfig(): void {
  validateSenderIdentity(EMAIL_FROM);
  if (!EMAIL_RE.test(SUPPORT_EMAIL)) {
    throw new Error('SUPPORT_EMAIL is invalid.');
  }
  if (REPLY_TO && !EMAIL_RE.test(REPLY_TO)) {
    throw new Error('REPLY_TO is invalid.');
  }
  getAppUrl();
  getResend();
}
